### ISSUE TITLE
关于面部阴影SDF阈值图

### ISSUE THREAD

**Issue by tom-choi** [Gaolingx/HonkaiStarRailToonShader#1]
面部阴影SDF是自己畫的 + 程序生成，还是模型底下拆包获取的？

[TestModels/星穹铁道—三月七/tex/FaceSDF.psd](https://github.com/Gaolingx/HonkaiStarRailToonShader/blob/main/TestModels/%E6%98%9F%E7%A9%B9%E9%93%81%E9%81%93%E2%80%94%E4%B8%89%E6%9C%88%E4%B8%83/tex/FaceSDF.psd)

**Comment by Gaolingx** [comment]
CSP等高线模糊，或者画图通过8seedt算法进行插值结合（注意输出32位以上，不然精度不够）
